// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/article/:category/:slug": {
    params: {
      "category": string;
      "slug": string;
    };
  };
  "/category/:category": {
    params: {
      "category": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/search" | "/article/:category/:slug" | "/category/:category";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/article.$category.$slug.tsx": {
    id: "routes/article.$category.$slug";
    page: "/article/:category/:slug";
  };
  "routes/category.$category.tsx": {
    id: "routes/category.$category";
    page: "/category/:category";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/article.$category.$slug": typeof import("./app/routes/article.$category.$slug.tsx");
  "routes/category.$category": typeof import("./app/routes/category.$category.tsx");
};